/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.samuelandrey.fuzzylogic;

import javax.swing.JOptionPane;

/**
 *
 * @author samuel
 */
public class FormMain extends javax.swing.JFrame {

    /**
     * Creates new form FormMain
     */
    public FormMain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtInputIpk = new javax.swing.JTextField();
        txtInputGaji = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lbIpkJelek = new javax.swing.JLabel();
        lbIpkSedang = new javax.swing.JLabel();
        lbIpkBagus = new javax.swing.JLabel();
        lbGajiRendah = new javax.swing.JLabel();
        lbGajiCukup = new javax.swing.JLabel();
        lbGajiTinggi = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lbKurang = new javax.swing.JLabel();
        lbLumayan = new javax.swing.JLabel();
        lbLayak = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnGenerate = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        lbSKurang = new javax.swing.JLabel();
        lbSLumayan = new javax.swing.JLabel();
        lbSLayak = new javax.swing.JLabel();
        lbKelayakan = new javax.swing.JLabel();
        btnReset = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        tabIpk = new javax.swing.JMenu();
        tabGaji = new javax.swing.JMenu();
        tabKelayakan = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("JetBrains Mono", 0, 24)); // NOI18N
        jLabel1.setText("Fuzzy Logic");

        txtInputIpk.setFont(new java.awt.Font("JetBrains Mono", 0, 12)); // NOI18N

        txtInputGaji.setFont(new java.awt.Font("JetBrains Mono", 0, 12)); // NOI18N
        txtInputGaji.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtInputGajiActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("JetBrains Mono", 0, 12)); // NOI18N
        jLabel3.setText("Input gaji orang tua (maks 12)");

        jLabel4.setFont(new java.awt.Font("JetBrains Mono", 0, 18)); // NOI18N
        jLabel4.setText("Didapatkan");

        lbIpkJelek.setFont(new java.awt.Font("JetBrains Mono", 0, 12)); // NOI18N
        lbIpkJelek.setText("IPK Jelek :");

        lbIpkSedang.setFont(new java.awt.Font("JetBrains Mono", 0, 12)); // NOI18N
        lbIpkSedang.setText("IPK Sedang :");

        lbIpkBagus.setFont(new java.awt.Font("JetBrains Mono", 0, 12)); // NOI18N
        lbIpkBagus.setText("IPK Bagus :");

        lbGajiRendah.setFont(new java.awt.Font("JetBrains Mono", 0, 12)); // NOI18N
        lbGajiRendah.setText("Gaji Rendah :");

        lbGajiCukup.setFont(new java.awt.Font("JetBrains Mono", 0, 12)); // NOI18N
        lbGajiCukup.setText("Gaji Cukup :");

        lbGajiTinggi.setFont(new java.awt.Font("JetBrains Mono", 0, 12)); // NOI18N
        lbGajiTinggi.setText("Gaji Tinggi :");

        jTable1.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Jelek", "Rendah", "Kurang"},
                {"Jelek", "Cukup", "Kurang"},
                {"Jelek", "Tinggi", "Kurang"},
                {"Sedang", "Rendah", "Lumayan"},
                {"Sedang", "Cukup", "Kurang"},
                {"Sedang", "Tinggi", "Kurang"},
                {"Bagus", "Rendah", "Layak"},
                {"Bagus", "Cukup", "Lumayan"},
                {"Bagus", "Tinggi", "Lumayan"}
            },
            new String [] {
                "IPK", "GAJI ORTU", "KELAYAKAN"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);

        jLabel11.setFont(new java.awt.Font("JetBrains Mono", 0, 18)); // NOI18N
        jLabel11.setText("Fuzzifikasi");

        jLabel5.setFont(new java.awt.Font("JetBrains Mono", 0, 12)); // NOI18N
        jLabel5.setText("Input ipk");

        lbKurang.setFont(new java.awt.Font("JetBrains Mono", 0, 12)); // NOI18N
        lbKurang.setText("Kurang = ");

        lbLumayan.setFont(new java.awt.Font("JetBrains Mono", 0, 12)); // NOI18N
        lbLumayan.setText("Lumayan =");

        lbLayak.setFont(new java.awt.Font("JetBrains Mono", 0, 12)); // NOI18N
        lbLayak.setText("Layak = ");

        jLabel9.setFont(new java.awt.Font("JetBrains Mono", 0, 18)); // NOI18N
        jLabel9.setText("Inferensi");

        btnGenerate.setFont(new java.awt.Font("JetBrains Mono", 3, 12)); // NOI18N
        btnGenerate.setText("Generate");
        btnGenerate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerateActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("JetBrains Mono", 0, 18)); // NOI18N
        jLabel10.setText("Defuzzifikasi");

        lbSKurang.setFont(new java.awt.Font("JetBrains Mono", 0, 12)); // NOI18N
        lbSKurang.setText("Sample Kurang =");

        lbSLumayan.setFont(new java.awt.Font("JetBrains Mono", 0, 12)); // NOI18N
        lbSLumayan.setText("Sample Lumayan =");

        lbSLayak.setFont(new java.awt.Font("JetBrains Mono", 0, 12)); // NOI18N
        lbSLayak.setText("Sample Layak =");

        lbKelayakan.setFont(new java.awt.Font("JetBrains Mono", 3, 14)); // NOI18N
        lbKelayakan.setText("Kelayakan");

        btnReset.setFont(new java.awt.Font("JetBrains Mono", 3, 12)); // NOI18N
        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lbIpkJelek, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtInputGaji)
                        .addComponent(jLabel1)
                        .addComponent(txtInputIpk)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE)
                        .addComponent(lbIpkSedang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbIpkBagus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbGajiRendah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbGajiCukup, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbGajiTinggi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel11)
                        .addComponent(btnGenerate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(107, 107, 107)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(lbLumayan, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbKurang, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbLayak, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(70, 70, 70)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(lbSKurang, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbSLumayan, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbSLayak, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbKelayakan, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addGap(66, 66, 66)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtInputIpk, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtInputGaji, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnGenerate, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbIpkJelek))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbSKurang)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbSLumayan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbSLayak)
                        .addGap(18, 18, 18)
                        .addComponent(lbKelayakan, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbKurang)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbLumayan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbLayak))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbIpkSedang)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbIpkBagus)
                        .addGap(18, 18, 18)
                        .addComponent(lbGajiRendah)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbGajiCukup)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbGajiTinggi)))
                .addGap(87, 87, 87)
                .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jMenu1.setText("Home");
        jMenuBar1.add(jMenu1);

        tabIpk.setText("Ipk");
        tabIpk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabIpkMouseClicked(evt);
            }
        });
        jMenuBar1.add(tabIpk);

        tabGaji.setText("Gaji");
        tabGaji.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabGajiMouseClicked(evt);
            }
        });
        jMenuBar1.add(tabGaji);

        tabKelayakan.setText("Kelayakan");
        tabKelayakan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabKelayakanMouseClicked(evt);
            }
        });
        jMenuBar1.add(tabKelayakan);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtInputGajiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtInputGajiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtInputGajiActionPerformed

    private void btnGenerateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerateActionPerformed
        FuzzyLogic fuzzy = new FuzzyLogic();
        
        try {
            double ipk = Double.parseDouble(txtInputIpk.getText());
            double gaji = Double.parseDouble(txtInputGaji.getText());
            
            if (ipk > 4) {
                throw new Exception();
            }
            

            // Tahap fuzzifikasi
            float ipkJelek = (float)fuzzy.leftTrapesium(ipk, 0, 2, 2.8);
            float ipkSedang = (float)fuzzy.triangle(ipk,  2, 2.8, 3.2);
            float ipkBagus = (float)fuzzy.rightTrapesium(ipk, 2.8, 3.2, 4 );

            lbIpkJelek.setText("Ipk Jelek ["+ipk+"] = " + ipkJelek);
            lbIpkSedang.setText("Ipk Sedang ["+ipk+"] = " + ipkSedang);
            lbIpkBagus.setText("Ipk Bagus ["+ipk+"] = " + ipkBagus);

            float gajiRendah = (float)fuzzy.leftTrapesium(gaji, 0, 2.5, 5);
            float gajiCukup = (float)fuzzy.triangle(gaji, 2.5, 5, 8);
            float gajiTinggi = (float)fuzzy.rightTrapesium(gaji, 5, 8, 12);

            lbGajiRendah.setText("Gaji Rendah ["+gaji+"] = " + gajiRendah);
            lbGajiCukup.setText("Gaji Cukup ["+gaji+"] = " + gajiCukup);
            lbGajiTinggi.setText("Gaji Tinggi ["+gaji+"] = " + gajiTinggi);

            fuzzy.inferensi(ipkJelek, gajiRendah, "kurang");
            fuzzy.inferensi(ipkJelek, gajiCukup, "kurang");
            fuzzy.inferensi(ipkJelek, gajiTinggi, "kurang");
            fuzzy.inferensi(ipkSedang, gajiRendah, "lumayan");
            fuzzy.inferensi(ipkSedang, gajiCukup, "kurang");
            fuzzy.inferensi(ipkSedang, gajiTinggi, "kurang");
            fuzzy.inferensi(ipkBagus, gajiRendah, "layak");
            fuzzy.inferensi(ipkBagus, gajiCukup, "lumayan");
            fuzzy.inferensi(ipkBagus, gajiTinggi, "lumayan");

            lbKurang.setText("Kurang = " + (float)fuzzy.kurang);
            lbLumayan.setText("Lumayan = " + (float)fuzzy.lumayan);
            lbLayak.setText("Layak = " + (float)fuzzy.layak);

            fuzzy.sample(0, 50, 80, 100);
            lbSKurang.setText("Sample Kurang = " + (float)fuzzy.sample1);
            lbSLumayan.setText("Sample Lumayan = " + (float)fuzzy.sample2);
            lbSLayak.setText("Sample Layak = " + (float)fuzzy.sample3);

            double result = fuzzy.defuzzification();
            lbKelayakan.setText("Kelayakan = " + (float)result);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Input tidak boleh kosong");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "IPK kok diatas 4??");
        }
        
    }//GEN-LAST:event_btnGenerateActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        txtInputIpk.setText("");
        txtInputIpk.setText("");
        
        lbIpkJelek.setText("IPK Jelek : ");
        lbIpkSedang.setText("IPK Sedang : ");
        lbIpkBagus.setText("IPK Bagus : ");
        
        lbGajiRendah.setText("Gaji Rendah : ");
        lbGajiCukup.setText("Gaji Cukup : ");
        lbGajiTinggi.setText("Gaji Tinggi : ");
        
        lbKurang.setText("Kurang = ");
        lbLumayan.setText("Lumayan = ");
        lbLayak.setText("Layak = ");
        
        lbSKurang.setText("Sample Kurang = ");
        lbSLumayan.setText("Sample Lumayan = ");
        lbSLayak.setText("Sample Layak = ");
        
        lbKelayakan.setText("Kelayakan");
    }//GEN-LAST:event_btnResetActionPerformed

    private void tabIpkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabIpkMouseClicked
        new Ipk();
    }//GEN-LAST:event_tabIpkMouseClicked

    private void tabGajiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabGajiMouseClicked
        new Gaji();
    }//GEN-LAST:event_tabGajiMouseClicked

    private void tabKelayakanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabKelayakanMouseClicked
        new Kelayakan();
    }//GEN-LAST:event_tabKelayakanMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGenerate;
    private javax.swing.JButton btnReset;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lbGajiCukup;
    private javax.swing.JLabel lbGajiRendah;
    private javax.swing.JLabel lbGajiTinggi;
    private javax.swing.JLabel lbIpkBagus;
    private javax.swing.JLabel lbIpkJelek;
    private javax.swing.JLabel lbIpkSedang;
    private javax.swing.JLabel lbKelayakan;
    private javax.swing.JLabel lbKurang;
    private javax.swing.JLabel lbLayak;
    private javax.swing.JLabel lbLumayan;
    private javax.swing.JLabel lbSKurang;
    private javax.swing.JLabel lbSLayak;
    private javax.swing.JLabel lbSLumayan;
    private javax.swing.JMenu tabGaji;
    private javax.swing.JMenu tabIpk;
    private javax.swing.JMenu tabKelayakan;
    private javax.swing.JTextField txtInputGaji;
    private javax.swing.JTextField txtInputIpk;
    // End of variables declaration//GEN-END:variables
}
